# Generated by Django 2.2.2 on 2019-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0002_auto_20190703_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='Nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='familia',
            name='codigo',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
