# Generated by Django 2.2.2 on 2019-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unidades',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Unidad', models.CharField(max_length=15)),
                ('Unidad_Basica', models.CharField(choices=[('KG', 'KILO'), ('GR', 'KILO'), ('LT', 'LITRO'), ('CC', 'LITRO'), ('UND', 'UNIDAD')], max_length=2)),
                ('Operador', models.CharField(choices=[('x', 'Multiplica'), ('%', ' Divide')], max_length=3)),
            ],
        ),
    ]
