# Generated by Django 2.2.2 on 2019-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unidades_Medida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidades',
            name='Factor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unidades',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Unidad_Basica',
            field=models.CharField(choices=[('KG', 'Kilo'), ('KG', 'Gramo'), ('LT', 'Litro'), ('LT', 'C.C'), ('UND', 'Unidad')], max_length=2),
        ),
    ]
